core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    AboutView,
    ShopListView,
    Terms,
    Privacy,
    Refunds,
    SellWithUs,
    Gallery,
    sell_with_us_two_form,
    ThankYouView
)
from . import views
app_name = 'core'

urlpatterns = [
    path('sell-with-us/', views.sell_with_us_two_form, name='sell-with-us'),
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('about/', AboutView.as_view(), name='about'),
    path('about.html', views.contact, name='contact'),
    path('shop-list/', ShopListView.as_view(), name='shop-list'),

    # Extras
    path('terms/', Terms.as_view(), name='terms'),
    path('privacy/', Privacy.as_view(), name='privacy'),
    path('refunds/', Refunds.as_view(), name='refunds'),
    path('thankyou/', ThankYouView.as_view(), name='thankyou'),

    # path('sellwithus/', SellWithUs.as_view(), name='sellwithus'),
    path('gallery/', Gallery.as_view(), name='gallery' )

]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Luxury'),
    ('SW', 'Casual'),
    ('OW', 'Dinner Party')
)

LABEL_CHOICES = (
    ('P', 'Special Offer'),
    ('S', 'Limited Edition'),
    ('D', 'New Collection'),
    ('N', 'Sold Out')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

STARE_CHOICES = (
    ('NE', 'Noua cu Etichete'),
    ('Noua Fara Etichete', 'Noua Fara Etichete'),
    ('Foarte Buna', 'Foarte Buna'),
    ('Buna', 'Buna'),
    ('Purtata', 'Purtata'),
    ('Prezinta Mici Defecte', 'Prezinta Mici Defecte'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, null=True, blank=True)
    slug = models.SlugField()
    description = models.TextField()

    # Images
    image = models.ImageField()
    image_fata = models.ImageField(null=True, blank=True)
    image_interior = models.ImageField(null=True, blank=True)
    image_lateral1 = models.ImageField(null=True, blank=True)
    image_lateral2 = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

class SellWIthUsTwo(models.Model):
    full_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField()
    phone = models.CharField(max_length=30, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    stare = models.CharField(choices=STARE_CHOICES, max_length=30, null=True, blank=True)
    pret = models.IntegerField()
    image = models.ImageField(null=True)
    image_2 = models.ImageField(null=True)
    image_3 = models.ImageField(null=True)
    image_4 = models.ImageField(null=True) 
    image_5 = models.ImageField(null=True)

    def __str__(self):
        return self.full_name
    

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    phone = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def __str__():
        return f"{self.first_name} {self.last_name}"

class Terms(models.Model):
    title_terms = models.CharField(max_length=250)
    content_terms = models.TextField(null=True)
    definitii = models.TextField(null=True) 
    dispozitii_generale = models.TextField(null=True) 
    reguli_de_utilizare = models.TextField(null=True) 
    proprietate_intelectuala = models.TextField(null=True) 
    informatiile_prezentate = models.TextField(null=True) 
    politica_de_vanzare = models.TextField(null=True) 
    contul = models.TextField(null=True) 
    comanda = models.TextField(null=True) 
    livrarea = models.TextField(null=True) 
    transferul_proprietatii= models.TextField(null=True) 
    facturare_plata = models.TextField(null=True) 
    conformitatea_produselor = models.TextField(null=True) 
    dreptu_denuntare = models.TextField(null=True) 
    gdpr = models.TextField(null=True) 
    promovare_produse_si_oferte = models.TextField(null=True) 
    raspundere = models.TextField(null=True) 
    sesizari = models.TextField(null=True) 
    ultima_legislatie = models.TextField(null=True) 

    def __str__(self):
        return self.title_terms

    class Meta:
        verbose_name_plural = 'Terms'


class Privacy(models.Model):
    title_privacy = models.CharField(max_length=250)
    content_privacy = models.TextField(null=True)

class Refunds(models.Model):
    title_refunds = models.CharField(max_length=250)
    content_refunds = models.TextField(null=True)

class SellWithUs(models.Model):
    item_title = models.CharField(max_length=250)
    item_description = models.TextField()

class Gallery(models.Model):
    gallery_title = models.CharField(max_length=250)

class ThankYou(models.Model):
    title = models.CharField(max_length=100, null=True)
    content = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.title

templates/footer.html
<!-- Footer Start -->
<footer class="footer border-top ptb--40 ptb-md--30">
  <div class="container">
    <div class="row mb--40 mb-md--30">
      <div class="col-lg-4 col-md-6 mb-md--30">
        <div class="footer-widget">
          <h3 class="widget-title">How to find us?</h3>
          <div class="widget-content mb--20">
            <p>
              Address: Calea Griviței 202, BUCUREȘTI
            </p>
            <div class="col-lg-8 d-flex align-items-center flex-column flex-lg-row">
          <ul class="social social-round mr--20">
            <li class="social__item">
              <a href="http://twitter.com" class="social__link__twitter">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li class="social__item">
              <a href="plus.google.com" class="social__link__google">
                <i class="fa fa-google-plus"></i>
              </a>
            </li>
            <li class="social__item">
              <a href="https://www.facebook.com/metanoiamasks" class="social__link__facebook">
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li class="social__item">
              <a href="http://youtube.com" class="social__link__youtube">
                <i class="fa fa-youtube"></i>
              </a>
            </li>
            <li class="social__item">
              <a href="https://www.instagram.com/metanoia_masks/" class="social__link__instagram">
                <i class="fa fa-instagram"></i>
              </a>
            </li>
          </ul>
        </div>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-6 mb-md--30">
        <div class="footer-widget">
          <h3 class="widget-title">Information</h3>
          <ul class="widget-menu">
            <li><a href="{% url 'core:about' %}">About Us</a></li>
            <li><a href="">Delivery Information</a></li>
            <li><a href="{% url 'core:privacy' %}">Privacy Policy</a></li>
            <li><a href="{% url 'core:terms' %}">Terms &amp; Conditions</a></li>
          </ul>
        </div>
      </div>
     
      <div class="col-lg-4 col-md-6">
        <div class="footer-widget">
          <h3 class="widget-title">
            <img src="/static/assets/img/logo/logo123.png" alt="logo" id="custom-log-mobile"/>
          </h3>
          <div class="widget-product">
            {% if item in object_list %}
            <div class="product">
              <div class="product-img">
                <img src="{{ item.image.url }}"alt="products" />
              </div>
              <div class="product-content">

                <h4 class="product-title">
                  <a href="{{ item.get_absolute_url }}" tabindex="0">{{ item.title }}</a>
                </h4>
                <div class="product-price-wrapper">
                  <span class="money">{{ item.price }}</span>
                </div>
              </div>
            </div>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
    <div class="row mb--40 mb-md--30">
      <div class="col-12">
        <ul class="footer-menu">
          <li><a href="">Home</a></li>
          <li><a href="">Privacy Policy</a></li>
          <li><a href="">Terms Of Use</a></li>
          <li><a href="">Contacts</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center">
        <p class="copyright-text">
          Copyright &copy; 2020 <a href="#">Metanoia</a>
        </p>

      </div>
    </div>
  </div>
</footer>
</div>
<!-- Footer End -->

templates/home.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
  <!-- Slider area Start -->

  <div class="slider-area">
    <div class="homepage-slider">
      <!-- Single Slide Start -->
      <div class="single-slider content-v-center" style="background-image: {% static 'assets/img/banner/banner1.jpg' %}">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <img src="{% static 'assets/img/banner/banner6.jpeg' %}" />
            </div>
          </div>
        </div>
      </div>
      <!-- Single Slide End -->

      <!-- Single Slide Start -->
      <div class="single-slider content-v-center" style="background-image: {% static 'assets/img/banner/banner1.jpg' %}">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <img src="{% static 'assets/img/banner/banner10.jpeg' %}" />
            </div>
          </div>
        </div>
      </div>
      <!-- Single Slide End -->



    </div>
  </div>
  <div class="col-xl-12">
    <div class="row">
      <div class="col-10 offset-1">
        <div class="about-text text-center">
          <h2 class="heading-secondary mb--40 mb-sm--30">
            THE STORY OF METANOIA
          </h2>
          <p class="mb--40 mb-sm--30">
            <strong>Metanoia (n.) the journey of altering one’s ways, beliefs and spiritual path.</strong>
            <br>
            <br>
            Bine ai venit in lumea Metanoia. O lume a lucrului frumos si facut din dragoste.
            Mentalitatea Metanoia are la baza idea ca lucrurile cu adevarat de valoare vor fi mereu la moda: everything old is new again.
            <br>
            <br>
            <strong>Ce ne defineste?
            Source, recycle, love again</strong>
            <br>
            <br>
            Cum functioneaza?
            Echipa Metanoia cauta produse textile vintage care apartin celor mai mari case de moda din lume. 
            Achizitionam esarfe si obiecte vestimentare de matase pentru a le oferi o a doua viata!
            Cele mai speciale piese de material devin un accesoriu esential vremurilor pe care le traim
            Piesele Metanoia sunt unicate, in cantitati limitate. Posted today, gone tomorrow!
          </p>
          <div class="about-btn-group text-center">
            <a href="{% url 'core:gallery' %}" class="btn btn-style-3">view our work</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Slider area End -->
  <!-- Most Viewed Product area Start -->
  <section class="mostviewed-product-area border-bottom pt--80 pb--60 pt-md--60 pb-md--50">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="section-title mb--15">
            <h2 class="color--black">Most Recent Products</h2>
          </div>
        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-12">
          <div class="product-carousel nav-top js-product-carousel-2">
            {% for item in object_list %}
            
            <div class="mirora-product">
              <div class="product-img">

                {% if item.image %}
                <a href="{{ item.get_absolute_url }}"><img src="{{ item.image.url }}" alt="Product" class="primary-image" /></a>
                {% endif %}

                {% if item.image_fata %}
                <a href="{{ item.get_absolute_url }}"><img src="{{ item.image_fata.url }}" alt="Product" class="secondary-image" /></a>
                {% endif %}

                <a href="{{ item.get_absolute_url }}">
                <div class="product-img-overlay">
                  <span class="product-label discount"> </span>
                  <!-- <a data-toggle="modal" data-target="#productModal" class="btn btn-transparent btn-fullwidth btn-medium btn-style-1">Quick View</a> -->
                </div>
                </a>
              </div>
              <div class="product-content text-center">
                <span>{{ item.get_category_display }}</span>
                <h4>
                  <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                </h4>
                <div class="product-price-wrapper">
                  <span class="money">{{ item.price }} LEI</span>
                </div>
              </div>
              <div class="mirora_product_action text-center position-absolute">

                <p>
                  {{ item.description }}
                </p>

                <div class="product-action">
                  <a class="add_cart cart-item action-cart" href="{{ item.get_add_to_cart_url }}" title="wishlist">
                    <span>Add to cart</span>
                  </a>

                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Most Viewed Product area End -->

  <!-- Banner area Start -->
  <section class="banner-area banner-bg-1 ptb--170 ptb-md--60">
    <div class="banner-box text-center">


      <a href="{% url 'core:shop-list' %}" class="btn btn-style-1">Shop Now</a>
    </div>
  </section>
  <!-- Banner area End -->

  {% for item in object_list %}
  <!-- Modal Start -->
  <!-- <div class="modal fade product-modal" id="productModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">Close</span>
          </button>
          <div class="container">
            <div class="row">
              <div class="col-lg-5 col-md-6 mb-sm--20">
                <div class="tab-content product-thumb-large">

                  {% if item.image %}
                  <div id="thumb1" class="tab-pane active show fade">
                    <img src="{{ item.image.url }}" alt="product thumb" />
                  </div>
                  {% endif %}

                  {% if item.image_lateral1 %}
                  <div id="thumb2" class="tab-pane fade">
                    <img src="{{ item.image_lateral1.url }}" alt="product thumb" />
                  </div>
                  {% endif %}

                </div>
                <div class="product-thumbnail">
                  <div class="thumb-menu" id="modal-thumbmenu">


                    <div class="thumb-menu-item">
                      <a href="#thumb1" data-toggle="tab" class="nav-link active">
                        <img src="{{ item.image.url }}" alt="product thumb" />
                      </a>
                    </div>

                    <div class="thumb-menu-item">
                      <a href="#thumb2" data-toggle="tab" class="nav-link">
                        <img src= alt="product thumb" />
                      </a>
                    </div>

                  </div>
                </div>
              </div>
              <div class="col-lg-7 col-md-6">
                <div class="modal-box product">
                  <h3 class="product-title">{{ item.title }}</h3>

                  <ul class="product-detail-list list-unstyled mb--20">
                    <li>Category: <a href="">Apple</a></li>
                    <li>Product Code: Watches</li>
                    <li>Reward Points: 600</li>
                    <li>Availability: In Stock</li>
                  </ul>
                  <div class="product-price border-bottom pb--20 mb--20">
                    <span class="regular-price">$100.50</span>
                    <span class="sale-price">$98.98</span>
                  </div>

                  <div class="product-action-wrapper mb--20">
                    <div class="product-action-top d-flex align-items-center mb--20">
                      <div class="quantity">
                        <input type="number" class="quantity-input" name="qty" id="qty" value="1" min="1" />
                      </div>
                      <button type="button" class="btn btn-medium btn-style-2 add-to-cart">
                        Add To Cart
                      </button>
                    </div>
                  </div>
                  <p class="product-tags">
                    Tags: <a href="shop.html">Sport</a>,
                    <a href="shop.html">Luxury</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> -->
  <!-- Modal End -->
  {% endfor %}


  <!-- Newsletter area End -->
  <div class="newsletter-area pt--40 pb--80 pt-md--30 pb-md--60">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-9 col-lg-10">
          <div class="newsletter text-center">
            <h3 class="color--white">Subscribe to Newsletter</h3>
            <p class="mb--40 mb-sm--30">
              <strong>BE UNAPOLOGETICALLY YOU</strong>
            </p>

            <form class="newsletter-form validate mt--40" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&id=05d85f18ef" method="post" id="mc-embedded-newsletter-form" name="mc-embedded-newsletter-form"
              target="_blank" novalidate="">
              <input type="email" name="email" id="sub_email" placeholder="Enter your email address here.." class="newsletter-form__input" />
              <input type="submit" value="Subscribe" class="btn newsletter-btn btn-style-1" />
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Newsletter area End -->
</div>
<!-- Main Content Wrapper Start -->

<!-- Scroll To Top Start -->


<div class="elfsight-app-e7c64518-d59b-40df-af45-b929699d7d8d"></div>

{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted"> {{ order_item.get_final_price }} LEI</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-{{ order.coupon.amount }} LEI</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (LEI)</span>
        <strong>LEi{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/shop-list.html
{% extends 'base.html' %} {% block content %}

<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
  <div class="shop-area pt--40 pb--80 pt-md--30 pb-md--60">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-12">
              <!-- Shop Toolbar Start -->
              <div class="shop-toolbar">
                <div class="product-view-mode" data-default="list">
                  <a class="grid-2" data-target="gridview-2" data-toggle="tooltip" data-placement="top" title="2">2</a>
                  <a class="grid-3" data-target="gridview-3" data-toggle="tooltip" data-placement="top" title="3">3</a>
                  <a class="grid-4" data-target="gridview-4" data-toggle="tooltip" data-placement="top" title="4">4</a>
                  <a class="grid-5" data-target="gridview-5" data-toggle="tooltip" data-placement="top" title="5">5</a>
                  <a class="activate list" data-target="listview" data-toggle="tooltip" data-placement="top" title="5">List</a>
                </div>

              </div>
              <!-- Shop Toolbar End -->
            </div>
          </div>

          <!-- Main Shop wrapper Start -->
          <div class="shop-product-wrap row no-gutters grid gridview-5">
            {% for item in object_list %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
              <div class="mirora-product mb-md--10">
                <div class="product-img">
                  {% if item.image %}
                  <img src="{{ item.image.url }}" alt="Product" class="primary-image" />
                  {% endif %}
                  {% if item.image_lateral1 %}
                  <img src="{{ item.image_lateral1.url }}" alt="Product" class="secondary-image" />
                  {% endif %}
                  <a href="{{ item.get_absolute_url }}">
                  <div class="product-img-overlay">
                    <span class="product-label discount">
                      {{ item.get_label_display }}
                    </span>
                  </div>
                  </a>
                </div>
                <div class="product-content text-center">
                  <span>{{ item.get_category_display }}</span>
                  <h4>
                    <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                  </h4>
                  <div class="product-price-wrapper">
                    <span class="money">{{ item.price }} LEI</span>
                  </div>
                </div>
                <div class="mirora_product_action text-center position-absolute">
                  <p>
                    {{ item.description }}
                  </p>

                  <div class="product-action">
                    <a class="add_cart cart-item action-cart" href="{{ item.get_add_to_cart_url }}" title="wishlist"><span>Add to cart</span></a>
                  </div>
                </div>
              </div>
              <div class="mirora-product-list">
                <div class="product-img">
                  {% if item.image %}
                  <img src="{{ item.image.url }}" alt="Product" class="primary-image" />
                  {% endif %}
                  {% if item.image_lateral1 %}
                  <img src="{{ item.image_lateral1.url }}" alt="Product" class="secondary-image" />
                  {% endif %}
                  <div class="product-img-overlay">
                    {% if item.label %}
                    <span class="product-label discount">
                      {{ item.get_label_display }}
                    </span>
                    {% endif %}
                    <!-- <a data-toggle="modal" data-target="#productModal" class="btn btn-transparent btn-fullwidth btn-medium btn-style-1">Quick View</a> -->
                  </div>
                </div>
                <div class="product-content">
                  <span>{{ item.get_category_display }}</span>
                  <h4>
                    <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                  </h4>

                  <p class="product-desc">
                    {{ item.description }}
                  </p>
                  <div class="product-price-wrapper">
                    <span class="money">{{ item.price }} LEI</span>

                    <div class="product-action">
                      <a class="add_cart cart-item action-cart" href="{{ item.get_add_to_cart_url }}" title="wishlist"><span>Add to cart</span></a>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

            <!-- Main Shop wrapper End -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Main Content Wrapper Start -->
<div class="elfsight-app-e7c64518-d59b-40df-af45-b929699d7d8d"></div>


{% endblock content %}

templates/thankyou.html
{% extends "base.html" %} {% load static %} {% block content %}

<main id="content" class="main-content-wrapper">
  <div class="error-area pt--90 pb--100">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-8 text-center">
          <div class="error">
            <h2>Iti multumim pentru comanda!</h2>
            <p>
              Echipa Metanoia te va contacta in cel mai scurt timp. 
              <br>
              Stay Safe & Chik
            </p>
            <a href="{% url 'core:home' %}" class="btn btn-4 btn-style-3">Back to home page</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock content %}